@startuml
autonumber 1 "<b>[0]"

actor "Payee" as Payee

participant "Beneficiary Management System" as BMS
box "Beneficiary Registration Portal" #LightBlue
participant "Beneficiary Registration Portal" as BRP
participant "SDK" as BSDK
end box

participant "MOSIP & e-Signet\nMISP" as eSignet

box "Payee DFSP"
participant "Mifos" as Mifos
participant "Mifos Core-Connector" as CC
participant "Token Adapter" as Adapter
participant "SDK" as SDK
end box
participant "Mojaloop" as Mojaloop  #d4f2f9

Payee->BMS: Payee initiates a\nPayment Token\nRegistration from the\nBeneficiary Management\nSystem
BMS->BRP: Redirected to\n Registration portal 
note left
 If a token is already 
 linked to that user,
 and needs to be modified,
 then this token should be
 provided.

 {
    PaymentToken:{}, (not part of POC)
    # registration will only support 
    # payment from this Payer
 }
end note

== MISP / MOSIP Authentication == 

BRP->eSignet: Redirects to /authorise API
activate BRP
eSignet->eSignet: Validates if claims \n is allowed by BRP
eSignet->Payee: Redirect to Authentication pages UI
Payee->eSignet: Enter Mosip auth detail with Mosip UIN / VID
Payee->eSignet: Users chooses method of authentication, and then meet challenge
eSignet-->BRP: return authorisation code
deactivate BRP
BRP->eSignet: Get Token
activate BRP
eSignet-->BRP: responds with ID token\n  and access token
deactivate BRP

== Select Mojaloop Payee Identifier == 

alt if this new registration

   BRP->Payee: Payee is asked to select a Payee Identifier Type
activate BRP
   Payee->BRP: Payee selects Payee Identifier Type (e.g. MSISDN or IBAN)
   BRP->Payee: Payee is asked to enter their Payee Identifier
   Payee->BRP: Payee selects Payee Identifier Type (e.g. +255 123 456 789)

else Existing token provided by Beneficiary Management System
   BRP->BRP: <color:Green> Lookup  from token using MOSIP PSUT
   BRP->Payee: <color:Green> Allow user to modify Payee Identifier
   Payee->BRP: <color:Green> Use update Payee Identifier and Type
end

BRP->>Mojaloop: GET \Parties\{Type}\{ID}    
note left
  Validate Payee Identifier by 
  calling Mojaloop discovery
end note
Mojaloop->>SDK: GET /parties/{Type}/{ID}
SDK->Adapter: GET /parties/{Type}/{ID}  
activate SDK
Adapter->CC: pass through
CC->Mifos: lookup Payee Identifier\naccount in Mifos
Mifos-->CC: return 
CC-->Adapter: return 
Adapter-->SDK: return Payee Name and personal details
deactivate SDK
SDK->>Mojaloop: PUT \Parties 
Mojaloop->>BRP: PUT \Parties
deactivate BRP

== Validate Personal Details == 

BRP->BRP: Retrieve personal details from \nPUT Parties response body
activate BRP
BRP->eSignet: Use MOSIP ID Token to access Personal Details
BRP->BRP: Validate PUT Parties Payee Name \nand personal details against MOSIP personal details
BRP->BRP: If provided validate ExternalId \nmatches MOSIP {UIN}
alt if personal details do not match
   BRP->Payee: Payee is asked to update their Payee Identifier
   Payee->BRP: Payee updates their Payee Identifier
   BRP->BRP: Repeat GET /parties call to mojaloop \nand validate Personal Details
else if personal details match
   BRP->BRP: Continue
end
deactivate BRP



@enduml