@startuml
autonumber 1 "<b>[0]"

actor "Payee" as Payee

participant "Beneficiary Management System" as BMS
box "Beneficiary Registration Portal" #LightBlue
participant "Beneficiary Registration Portal" as BRP
participant "SDK" as BSDK
end box

participant "MOSIP & e-Signet\nMISP" as eSignet

box "Payee DFSP"
participant "Mifos" as Mifos
participant "Mifos Core-Connector" as CC
participant "Token Adapter" as Adapter
participant "SDK" as SDK
end box
participant "Mojaloop" as Mojaloop  #d4f2f9

=== P2P Using Mosip Payment Token ==

Mojaloop->Mojaloop: Discovery call \n initiated
Mojaloop->>SDK: **GET** \n /parties/ALIAS/{PaymentToken}
SDK->Adapter: **GET** \n /parties/ALIAS/{PaymentToken}
activate Adapter
Adapter->Adapter: Lookup Payment Token \n with mapped Itentifier \nand type from cache 
Adapter->CC: **GET** \n /parties/{PayeeIdentifierType}/{PayeeIdentifier}
deactivate Adapter

CC->CC: Get Payment Token from cache
CC->Mifos: **GET** api/v1/clients/{ID}/accounts
note left
  Get Client Account details

  <i>Note:</i>
  There's no way to provide access only to 1 account!
end note
CC->CC: Find and validate particular account \n (based on token data)

alt Account exists and active
    CC->Mifos: **GET** api/v1/clients/{ID}
    note left
       Get client details
    end note
    CC-->Adapter:  Yes. This is Joe's Blogs account.
    note left
       Payload:
         {
            "party": {
                "name": "Joe Blogs",
                "partyIdInfo":{
                      "partyIdType": {ALIAS},
                      "partyIdentifier":{PaymentToken},
                      ...
                }
            }
         }
    end note
    Adapter-->SDK:  Yes. This is Joe's Blogs account.
else
    CC --> Adapter: Party error response
    Adapter --> SDK: Party error response
end

deactivate SDK

SDK->>Mojaloop: **PUT** /getParties \n Yes. This is Joe's Blogs account.
Mojaloop->Mojaloop: Continue with\n  standard P2P

Mojaloop->Mojaloop: Quotes call initiated
Mojaloop->>SDK: **POST** /quotes
SDK->Adapter:  **POST** /quoterequest
activate SDK

activate Adapter
Adapter->Adapter: Lookup Payment Token \n with mapped Itentifier \nand type from cache 
Adapter->CC: **POST** /quoterequest
deactivate Adapter

CC->CC: Get Payment Token from cache
CC->Mifos: **GET** api/v1/clients/{ID}/accounts
note left
  Validate if Client Account is active
end note
CC->CC: Process quote request
CC-->Adapter: Return quote
Adapter-->SDK: Return quote
deactivate SDK
SDK->>Mojaloop: **PUT** /quotes 

Mojaloop->Mojaloop: Continue with \n standard P2P

Mojaloop->Mojaloop: Transact call \n initiated
Mojaloop->>SDK: **POST** /transfers

SDK->Adapter:  **POST** /transfers
activate Adapter
Adapter->Adapter: Lookup Payment Token \n with mapped Itentifier \nand type from cache 
Adapter->CC: **POST** /transfers
deactivate Adapter
activate SDK
CC->CC: Get Payment Token from cache
CC->CC: Validate quote
CC-->Adapter:  TransferState=RESERVED
Adapter-->SDK:  TransferState=RESERVED
SDK->>Mojaloop: **PUT** /transfers
Mojaloop->>SDK: **PATCH** /transfers
SDK->Adapter: **PATCH** /transfers
activate Adapter
Adapter->Adapter: Lookup Payment Token \n with mapped Itentifier \nand type from cache 
Adapter->CC: **PATCH** /transfers
deactivate Adapter

CC->CC: Get Payment Token from cache
CC->Mifos: **GET** api/v1/clients/{ID}/accounts
note left
  Validate if Client Account is active
end note

CC->Mifos: **POST** api/v1/accounttransfers
note left
  Transfer of funds from prefunded liquidity account to party's account
  docs: [[https://demo.mifos.io/api-docs/apiLive.htm#accounttransfer]]

  Payload:
    {
      "fromOfficeId":1,
      "fromClientId":1,
      "fromAccountType":2,
      "fromAccountId":1,
      "toOfficeId":1,
      "toClientId":1,
      "toAccountType":2,
      "toAccountId":2,
      "dateFormat":"dd MMMM yyyy",
      "locale":"en",
      "transferDate":"01 August 2011",
      "transferAmount":"112.45",
      "transferDescription":"A description of the transfer"
    }

    <i>Note:</i>
       **from...**-fields are configured
end note
CC-->Adapter:  return
Adapter-->SDK:  return
deactivate SDK
@enduml
