@startuml
autonumber 1 "<b>[0]"

actor "Payee" as Payee

participant "Beneficiary Management System" as BMS
box "Beneficiary Registration Portal" #LightBlue
participant "Beneficiary Registration Portal" as BRP
participant "SDK" as BSDK
end box

participant "MOSIP & e-Signet\nMISP" as eSignet

box "Payee DFSP"
participant "Mifos" as Mifos
participant "Mifos Core-Connector" as CC
participant "Token Adapter" as Adapter
participant "SDK" as SDK
end box
participant "Mojaloop" as Mojaloop  #d4f2f9

== PaymentToken selection ==

alt use MOSIP token
BRP->BRP: Use Returned Mosip token \n (This may be either UIN \n of Mosip Token depends \n on what is made available)
else generate cryptographically interlocked token
BRP->BRP: <color:Green> Create new Token for \nPayee cryptographically \ninterlocked between MOSIP\n token Payee and Payer \n (not part of POC)
else generate new token
BRP->BRP: <color:Green> Create new Global Token for Payee\n  (not part of POC)
end


== Deregister existing Payment Token ==
BRP->Adapter: <color:Green> Deregister Payment Token (not part of POC)
note left
**DELETE** users/{PSUT}/tokens/{PaymentToken}

<i>PSUT</i> (Partner Specific User Token)
       Unique identifier of user provided by MOSIP login

end note
activate BRP

Adapter->Adapter: Delete Payment Token from cache

Adapter-->BRP: <color:Green> return success

BRP->BSDK: <color:Green> **DELETE** /accounts 
BSDK->>Mojaloop: <color:Green> **DELETE** \n /participants/ALIAS/{PaymentToken}
Mojaloop->>BSDK: <color:Green> **PUT** \n /participants/ALIAS/{PaymentToken}
BSDK-->BRP: <color:Green> return success
deactivate BRP

== Register Payment Token ==

BRP->BRP: Token stored in perisistant cache
note left
**PSUT**: #(Partner Specific User Token)
          # Unique identifier of user provided by MOSIP login
{
    PaymentToken, # Party Id for Payee
    PayeeId, # Mojaloop Payee Identifier
    PayeeItentifierType # Mojaloop Payee Identifier Type
}
end note




BRP->Adapter: <color:Blue> Configure Adapater with Token
note left
**POST** users/{PSUT}/tokens
{
    PaymentToken, # Party Id for Payee
    PayeeId, # Mojaloop Payee Identifier
    PayeeItentifierType # Mojaloop Payee Identifier Type
}

<i>PSUT</i> (Partner Specific User Token)
       Unique identifier of user provided by MOSIP login
end note

Adapter->Adapter: Store Payment Token in cache
Adapter-->BRP: return success

BRP->BSDK: **POST** /accounts
note left 
Register Payment Token in Mojaloop Oracle
end note
BSDK->>Mojaloop: **POST** \n /participants/ALIAS/{PaymentToken} \n register payment token in alias
Mojaloop->>BSDK: **PUT** \n /participants/ALIAS/{PaymentToken}
BSDK-->BRP: return

deactivate BRP

@enduml
